### ISSUE TITLE
Negative numbers always

### ISSUE THREAD

**Issue by hghgsat** [bahlo/homebridge-temperature-file#3]
Hi,
negative numbers in my file are always 0.
positive numbers works fine.

![image](https://user-images.githubusercontent.com/12203069/105537812-c57bd480-5cf2-11eb-84de-686886d7e0eb.png)

![image](https://user-images.githubusercontent.com/12203069/105537782-b85ee580-5cf2-11eb-87b9-a87adabf6e98.png)

added 
            "MaxValue": 100,
            "MinValue": -100

to the config but did not resolved the issue.

thx
Harry

**Comment by hghgsat** [comment]
added to index.js and now it works with negative numbers too

![image](https://user-images.githubusercontent.com/12203069/105540695-e5ad9280-5cf6-11eb-9c32-24ed38cc1388.png)

**Comment by bahlo** [comment]
Awesome, would you mind creating a PR?

**Comment by hghgsat** [comment]
there is already an PR with the same suggestions and other ideas how to handle negative numbers/using config etc...

**Comment by hghgsat** [comment]
now two PRs...

**Comment by bahlo** [comment]
Closed via !4, thanks!
